on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["amd64", "arm64", "armv"]
    steps:
      - name: Install deps
        run: |
           sudo apt-get update -q -y
           sudo apt-get -qq install -y qemu qemu-user-static
           docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
      - name: Setup
        run: |
          mkdir artifacts
      - name: Fetch and extract
        run: |
          docker pull --platform "linux/${{ matrix.platform }}" vaultwarden/server:latest
          docker run --platform "linux/${{ matrix.platform }}" --name "vaultwarden" -d -t vaultwarden/server
          docker cp vaultwarden:/vaultwarden ./artifacts/vaultwarden_${{ matrix.platform }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            ./artifacts/vaultwarden_${{ matrix.platform }}
